# -*- coding: utf-8 -*-
"""Print_LinkedList_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcmVfkkslgCan737Why8QCtCBY29yIRz
"""

# Read a full line of input from stdin and save it to our dynamically typed variable, input_string.
input_string = input()

# Print a string literal saying "Hello, World." to stdout.
print("Hello, World.")

# TODO: Write a line of code here that prints the contents of input_string to stdout.

print(input_string)

i = 4
d = 4.0
s = 'HackerRank '
var1 = None
var2 = None
var3 = None

var1 = int(input())
var2 = float(input())
var3 = str(input())

print(i+var1)
print(d+var2)
print(s+var3)

#!/bin/python3

import math
import os
import random
import re
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

# Complete the printLinkedList function below.

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
#
#
def print_list(head):
    node = head
    while node != None:
        print(node.data)
        node = node.next
if __name__ == '__main__':
    llist_count = int(input())

    llist = SinglyLinkedList()

    for _ in range(llist_count):
        llist_item = int(input())
        llist.insert_node(llist_item)

    print_list(llist.head)

